#ifndef GLVISION_KEYS_H__
#define GLVISION_KEYS_H__

enum GLVISION_KEY
{
    GLVISION_KEY_SPACE =             32,
    GLVISION_KEY_APOSTROPHE =        39,
    GLVISION_KEY_PLUS =              43,
    GLVISION_KEY_COMMA =             44,
    GLVISION_KEY_MINUS =             45,
    GLVISION_KEY_PERIOD =            46,
    GLVISION_KEY_SLASH =             47,
    GLVISION_KEY_0 =                 48,
    GLVISION_KEY_1 =                 49,
    GLVISION_KEY_2 =                 50,
    GLVISION_KEY_3 =                 51,
    GLVISION_KEY_4 =                 52,
    GLVISION_KEY_5 =                 53,
    GLVISION_KEY_6 =                 54,
    GLVISION_KEY_7 =                 55,
    GLVISION_KEY_8 =                 56,
    GLVISION_KEY_9 =                 57,
    GLVISION_KEY_SEMICOLON =         58,
    GLVISION_KEY_EQUAL =             61,
    GLVISION_KEY_A =                 65,
    GLVISION_KEY_B =                 66,
    GLVISION_KEY_C =                 67,
    GLVISION_KEY_D =                 68,
    GLVISION_KEY_E =                 69,
    GLVISION_KEY_F =                 70,
    GLVISION_KEY_G =                 71,
    GLVISION_KEY_H =                 72,
    GLVISION_KEY_I =                 73,
    GLVISION_KEY_J =                 74,
    GLVISION_KEY_K =                 75,
    GLVISION_KEY_L =                 76,
    GLVISION_KEY_M =                 77,
    GLVISION_KEY_N =                 78,
    GLVISION_KEY_O =                 79,
    GLVISION_KEY_P =                 80,
    GLVISION_KEY_Q =                 81,
    GLVISION_KEY_R =                 82,
    GLVISION_KEY_S =                 83,
    GLVISION_KEY_T =                 84,
    GLVISION_KEY_U =                 85,
    GLVISION_KEY_V =                 86,
    GLVISION_KEY_W =                 87,
    GLVISION_KEY_X =                 88,
    GLVISION_KEY_Y =                 89,
    GLVISION_KEY_Z =                 90,
    GLVISION_KEY_LEFT_BRACKET =      91,
    GLVISION_KEY_BACKSLASH =         92,
    GLVISION_KEY_RIGHT_BRACKET =     93,
    GLVISION_KEY_a =                 97,
    GLVISION_KEY_b =                 98,
    GLVISION_KEY_c =                 99,
    GLVISION_KEY_d =                 100,
    GLVISION_KEY_e =                 101,
    GLVISION_KEY_f =                 102,
    GLVISION_KEY_g =                 103,
    GLVISION_KEY_h =                 104,
    GLVISION_KEY_i =                 105,
    GLVISION_KEY_j =                 106,
    GLVISION_KEY_k =                 107,
    GLVISION_KEY_l =                 108,
    GLVISION_KEY_m =                 109,
    GLVISION_KEY_n =                 110,
    GLVISION_KEY_o =                 111,
    GLVISION_KEY_p =                 112,
    GLVISION_KEY_q =                 113,
    GLVISION_KEY_r =                 114,
    GLVISION_KEY_s =                 115,
    GLVISION_KEY_t =                 116,
    GLVISION_KEY_u =                 117,
    GLVISION_KEY_v =                 118,
    GLVISION_KEY_w =                 119,
    GLVISION_KEY_x =                 120,
    GLVISION_KEY_y =                 121,
    GLVISION_KEY_z =                 122,
    GLVISION_KEY_ESCAPE,
    GLVISION_KEY_ENTER,          
    GLVISION_KEY_TAB,            
    GLVISION_KEY_BACKSPACE,      
    GLVISION_KEY_INSERT,         
    GLVISION_KEY_DELETE,            
    GLVISION_KEY_RIGHT,             
    GLVISION_KEY_LEFT,               
    GLVISION_KEY_DOWN,               
    GLVISION_KEY_UP,         
    GLVISION_KEY_PAGE_UP,   
    GLVISION_KEY_PAGE_DOWN,      
    GLVISION_KEY_HOME,    
    GLVISION_KEY_END,     
    GLVISION_KEY_F1,        
    GLVISION_KEY_F2,          
    GLVISION_KEY_F3,       
    GLVISION_KEY_F4,   
    GLVISION_KEY_F5,      
    GLVISION_KEY_F6,     
    GLVISION_KEY_F7,     
    GLVISION_KEY_F8,     
    GLVISION_KEY_F9,    
    GLVISION_KEY_F10,    
    GLVISION_KEY_F11,    
    GLVISION_KEY_F12,
    GLVISION_KEY_UNDEFINED = 999,
};

enum GLVISION_MOUSE {
    GLVISION_MOUSE_BUTTON_LEFT,
    GLVISION_MOUSE_BUTTON_MIDDLE,
    GLVISION_MOUSE_BUTTON_RIGHT,
    GLVISION_MOUSE_UNDEFINED = 999
};

enum GLVISION_KEY_STATE {
    GLVISION_KEY_STATE_PRESS,
    GLVISION_KEY_STATE_RELEASE
};

#endif